pipeline {
    agent none

    stages {
        stage('Docker on Host') {
            agent any
            steps {
                sh 'docker ps'
            }
        }
        stage('Node Test in Container') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
