pipeline {
    agent {
        docker {
            image 'node:16-alpine'
        }
    }

    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }

        stage('Docker Permission Test') {
            steps {
                sh 'whoami'
                sh 'docker ps'
            }
        }
    }
}
